"""`loopy.events` codegen — emit typed event definitions from the registry so sensor
authors get types their own typechecker validates. Multi-target behind `CodegenTarget`
(Python first; `.d.ts` etc. additive). Author-facing only — Core reads each sensor's
declared `emits`, not these types.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from loopy_core.registry.model import Registry

_SCALAR = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
}


def _annotation(schema: dict) -> str:
    if schema.get("type") == "string" and "enum" in schema:
        return "Literal[" + ", ".join(repr(v) for v in schema["enum"]) + "]"
    return _SCALAR.get(schema.get("type"), "Any")


class CodegenTarget(Protocol):
    def generate(self, registry: Registry) -> dict[str, str]:
        """Return {relative_path: file_contents} for this language target."""
        ...


class PythonTarget:
    """Emit a `loopy/events.py` pydantic module + `events.pyi` stub + package init."""

    def generate(self, registry: Registry) -> dict[str, str]:
        return {
            # Re-export the authoring shim so user sensors can `from loopy import sensor`.
            "loopy/__init__.py": (
                "# Generated by `loopy compile`. Do not edit.\n"
                "from loopy_runtime.authoring import sensor\n\n"
                '__all__ = ["sensor"]\n'
            ),
            "loopy/events.py": self._module(registry),
            "loopy/events.pyi": self._stub(registry),
        }

    def _module(self, registry: Registry) -> str:
        lines = [
            "# Generated by `loopy compile` from registry.yml. Do not edit.",
            "from typing import Any, Literal",
            "",
            "from pydantic import BaseModel",
            "",
        ]
        for name in sorted(registry.events):
            lines.append("")
            lines.append(f"class {name}(BaseModel):")
            fields = registry.events[name].fields
            if not fields:
                lines.append("    pass")
                continue
            for field in sorted(fields):
                lines.append(f"    {field}: {_annotation(fields[field])}")
        return "\n".join(lines) + "\n"

    def _stub(self, registry: Registry) -> str:
        lines = [
            "from typing import Any, Literal",
            "",
            "from pydantic import BaseModel",
            "",
        ]
        for name in sorted(registry.events):
            lines.append("")
            lines.append(f"class {name}(BaseModel):")
            fields = registry.events[name].fields
            if not fields:
                lines.append("    ...")
                continue
            for field in sorted(fields):
                lines.append(f"    {field}: {_annotation(fields[field])}")
        return "\n".join(lines) + "\n"


TARGETS: dict[str, CodegenTarget] = {"python": PythonTarget()}


def generate_events(registry: Registry, target: str = "python") -> dict[str, str]:
    return TARGETS[target].generate(registry)


def write_events(registry: Registry, out_dir: str | Path, target: str = "python") -> list[Path]:
    """Write the generated event files under `out_dir`, returning the paths written."""
    out_dir = Path(out_dir)
    written: list[Path] = []
    for relpath, content in generate_events(registry, target).items():
        path = out_dir / relpath
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(path)
    return written
