"""`loopy dockerfile` and `loopy env` — the git-push deploy generators.

`loopy dockerfile` emits a version-pinned Dockerfile + .dockerignore so a platform can build
the engine from a git push; `loopy env` prints the production env block to paste into the
platform, forwarding each sandbox's declared `env:` keys under their `<PREFIX>_<KEY>` namespace.
"""

from __future__ import annotations

from typer.testing import CliRunner

from loopy_cli import app
from loopy_core import __version__

runner = CliRunner()

_REGISTRY = (
    "sandboxes:\n"
    "  BaseSandbox:\n"
    "    provider: daytona\n"
    "    env_file: secrets/base.env\n"
    "    env: [ANTHROPIC_API_KEY, GITHUB_TOKEN]\n"
    "agents:\n"
    "  Worker: { model: claude-sonnet-4-6, harness: claude-code, sandbox: BaseSandbox }\n"
)
_SECRETS = "ANTHROPIC_API_KEY=sk-ant-real\nGITHUB_TOKEN=ghp_real\nOPENAI_API_KEY=sk-undeclared\n"
_LOOPY_ENV = (
    "DAYTONA_API_KEY=dt-real\n"
    "LOOPY_ADMIN_TOKEN=loopy_sk_admin\n"
    "REDIS_URL=redis://localhost:6379\n"
    "LOOPY_PUBLIC_URL=https://tunnel.example.com\n"
)


def _project(tmp_path):
    (tmp_path / "registry.yml").write_text(_REGISTRY)
    (tmp_path / "secrets").mkdir()
    (tmp_path / "secrets" / "base.env").write_text(_SECRETS)
    (tmp_path / "loopy.env").write_text(_LOOPY_ENV)
    return tmp_path


# ── loopy dockerfile ────────────────────────────────────────────────────────────


def test_dockerfile_stdout_is_version_pinned(tmp_path):
    result = runner.invoke(app, ["dockerfile", str(_project(tmp_path)), "--stdout"])
    assert result.exit_code == 0
    assert f'"loopy-computer[redis]=={__version__}"' in result.stdout
    assert '"--in-process"' in result.stdout
    assert '"--bus"' not in result.stdout  # CMD passes no bus flag; auto-selected from REDIS_URL
    assert "RUN loopy compile ." in result.stdout  # build gate
    # --stdout writes nothing
    assert not (tmp_path / "Dockerfile").exists()


def test_dockerfile_writes_both_files(tmp_path):
    result = runner.invoke(app, ["dockerfile", str(_project(tmp_path))])
    assert result.exit_code == 0
    assert (tmp_path / "Dockerfile").read_text().startswith("# Generated by `loopy dockerfile`")
    dockerignore = (tmp_path / ".dockerignore").read_text()
    # The .dockerignore is load-bearing: it keeps secrets out of a local image build.
    assert "loopy.env" in dockerignore
    assert "secrets/" in dockerignore
    # Excludes dotenv files anywhere, so a non-default env_file path is covered too.
    assert "**/*.env" in dockerignore


def test_dockerfile_rejects_nonexistent_directory(tmp_path):
    result = runner.invoke(app, ["dockerfile", str(tmp_path / "nope")])
    assert result.exit_code == 1
    # A clean typer.Exit, not an uncaught FileNotFoundError traceback.
    assert isinstance(result.exception, SystemExit)
    assert not (tmp_path / "nope").exists()  # no partial write / dir creation


def test_dockerfile_overwrites_existing(tmp_path):
    # The files are generated artifacts pinned to the loopy version, so regenerating overwrites
    # an existing Dockerfile in place (keeps the pin current after an upgrade) — no flag needed.
    project = _project(tmp_path)
    (project / "Dockerfile").write_text("hand-written")
    result = runner.invoke(app, ["dockerfile", str(project)])
    assert result.exit_code == 0
    assert (project / "Dockerfile").read_text().startswith("# Generated")


# ── loopy env ─────────────────────────────────────────────────────────────────


def test_env_emits_control_plane_values(tmp_path):
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    assert result.exit_code == 0
    assert "DAYTONA_API_KEY=dt-real" in result.stdout
    assert "LOOPY_ADMIN_TOKEN=loopy_sk_admin" in result.stdout


def test_env_replaces_redis_url_with_placeholder(tmp_path):
    # The local localhost value is useless in production; emit an editable placeholder instead.
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    assert "redis://localhost:6379" not in result.stdout
    assert "REDIS_URL=redis://…" in result.stdout


def test_env_omits_laptop_side_public_url(tmp_path):
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    # The value never appears; only a comment explaining where it lives.
    assert "https://tunnel.example.com" not in result.stdout
    assert "LOOPY_PUBLIC_URL is laptop-side" in result.stdout


def test_env_forwards_declared_sandbox_keys_namespaced(tmp_path):
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    assert "BASESANDBOX_ANTHROPIC_API_KEY=sk-ant-real" in result.stdout
    assert "BASESANDBOX_GITHUB_TOKEN=ghp_real" in result.stdout


def test_env_excludes_undeclared_env_file_keys(tmp_path):
    # OPENAI_API_KEY is in the env_file but not declared in env:, so it is not forwarded.
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    assert "OPENAI" not in result.stdout


def test_env_missing_env_file_yields_empty_placeholders(tmp_path):
    # A declared env_file that isn't on disk must not crash; keys emit with empty values.
    (tmp_path / "registry.yml").write_text(_REGISTRY)
    (tmp_path / "loopy.env").write_text(_LOOPY_ENV)
    result = runner.invoke(app, ["env", str(tmp_path)])
    assert result.exit_code == 0
    assert "BASESANDBOX_ANTHROPIC_API_KEY=" in result.stdout


def test_env_fails_on_uncompilable_project(tmp_path):
    # A project that doesn't compile (reserved env: key, E216) must not emit a deploy block.
    (tmp_path / "registry.yml").write_text(
        "sandboxes:\n  BaseSandbox:\n    provider: local\n    env: [DAYTONA_API_KEY]\n"
    )
    result = runner.invoke(app, ["env", str(tmp_path)])
    assert result.exit_code == 1
