"""`loopy dockerfile` and `loopy env` — the git-push deploy generators.

`loopy dockerfile` emits a version-pinned Dockerfile + .dockerignore so a platform can build
the engine from a git push; `loopy env` prints the engine's control-plane env block to paste
into the platform (sandbox secrets ride each sandbox's own `env_file`, not this block).
"""

from __future__ import annotations

from typer.testing import CliRunner

from loopy_cli import app
from loopy_core import __version__

runner = CliRunner()

_REGISTRY = (
    "sandboxes:\n"
    "  BaseSandbox:\n"
    "    provider: daytona\n"
    "    env_file: secrets/base.env\n"
    "agents:\n"
    "  Worker: { model: claude-sonnet-4-6, harness: claude-code, sandbox: BaseSandbox }\n"
)
_SECRETS = "ANTHROPIC_API_KEY=sk-ant-real\nGITHUB_TOKEN=ghp_real\nOPENAI_API_KEY=sk-undeclared\n"
_LOOPY_ENV = (
    "DAYTONA_API_KEY=dt-real\n"
    "LOOPY_ADMIN_TOKEN=loopy_sk_admin\n"
    "REDIS_URL=redis://localhost:6379\n"
    "LOOPY_PUBLIC_URL=https://tunnel.example.com\n"
)


def _project(tmp_path):
    (tmp_path / "registry.yml").write_text(_REGISTRY)
    (tmp_path / "secrets").mkdir()
    (tmp_path / "secrets" / "base.env").write_text(_SECRETS)
    (tmp_path / "loopy.env").write_text(_LOOPY_ENV)
    return tmp_path


# ── loopy dockerfile ────────────────────────────────────────────────────────────


def test_dockerfile_stdout_is_version_pinned(tmp_path):
    result = runner.invoke(app, ["dockerfile", str(_project(tmp_path)), "--stdout"])
    assert result.exit_code == 0
    assert f'"loopy-computer[redis]=={__version__}"' in result.stdout
    assert "--in-process" in result.stdout
    assert "--bus" not in result.stdout  # no bus flag; auto-selected from REDIS_URL
    assert "RUN loopy compile ." in result.stdout  # build gate
    assert not (tmp_path / "Dockerfile").exists()


def test_dockerfile_start_command_links_secret_files_and_honors_port(tmp_path):
    result = runner.invoke(app, ["dockerfile", str(_project(tmp_path)), "--stdout"])
    assert result.exit_code == 0
    assert "/etc/secrets" in result.stdout  # Render secret files get linked into place
    assert "s|__|/|g" in result.stdout  # flat names decode back to nested paths
    assert "${PORT:-8000}" in result.stdout  # platform-injected port wins
    assert "/state/state.db" in result.stdout  # a mounted /state disk gets durable history


def test_dockerfile_cmd_is_valid_json_and_sh(tmp_path):
    # The CMD rides Dockerfile line continuations inside an exec-form JSON array — parse it
    # the way Docker does (join `\`-newline, then JSON) and syntax-check the sh payload, so
    # a bad escape in the template fails here instead of on the first real platform build.
    import json
    import shutil
    import subprocess

    import pytest

    if shutil.which("sh") is None:  # pragma: no cover - POSIX always has sh
        pytest.skip("sh unavailable")
    result = runner.invoke(app, ["dockerfile", str(_project(tmp_path)), "--stdout"])
    assert result.exit_code == 0
    joined = result.stdout.replace("\\\n", "")
    cmd_line = next(line for line in joined.splitlines() if line.startswith("CMD "))
    argv = json.loads(cmd_line[len("CMD ") :])
    assert argv[:2] == ["/bin/sh", "-c"]
    check = subprocess.run(["sh", "-n"], input=argv[2], text=True, capture_output=True)
    assert check.returncode == 0, check.stderr


def test_dockerfile_writes_both_files(tmp_path):
    result = runner.invoke(app, ["dockerfile", str(_project(tmp_path))])
    assert result.exit_code == 0
    assert (tmp_path / "Dockerfile").read_text().startswith("# Generated by `loopy dockerfile`")
    dockerignore = (tmp_path / ".dockerignore").read_text()
    # The .dockerignore is load-bearing: it keeps secrets out of a local image build.
    assert "loopy.env" in dockerignore
    assert "secrets/" in dockerignore
    # Excludes dotenv files anywhere, so a non-default env_file path is covered too.
    assert "**/*.env" in dockerignore


def test_dockerfile_rejects_nonexistent_directory(tmp_path):
    result = runner.invoke(app, ["dockerfile", str(tmp_path / "nope")])
    assert result.exit_code == 1
    # A clean typer.Exit, not an uncaught FileNotFoundError traceback.
    assert isinstance(result.exception, SystemExit)
    assert not (tmp_path / "nope").exists()  # no partial write / dir creation


def test_dockerfile_overwrites_existing(tmp_path):
    # The files are generated artifacts pinned to the loopy version, so regenerating overwrites
    # an existing Dockerfile in place (keeps the pin current after an upgrade) — no flag needed.
    project = _project(tmp_path)
    (project / "Dockerfile").write_text("hand-written")
    result = runner.invoke(app, ["dockerfile", str(project)])
    assert result.exit_code == 0
    assert (project / "Dockerfile").read_text().startswith("# Generated")


# ── loopy env ─────────────────────────────────────────────────────────────────


def test_env_emits_control_plane_values(tmp_path):
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    assert result.exit_code == 0
    assert "DAYTONA_API_KEY=dt-real" in result.stdout
    assert "LOOPY_ADMIN_TOKEN=loopy_sk_admin" in result.stdout


def test_env_replaces_redis_url_with_placeholder(tmp_path):
    # The local localhost value is useless in production; emit an editable placeholder instead.
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    assert "redis://localhost:6379" not in result.stdout
    assert "REDIS_URL=redis://…" in result.stdout


def test_env_omits_dev_side_public_url(tmp_path):
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    # The value never appears; only a comment explaining where it lives.
    assert "https://tunnel.example.com" not in result.stdout
    assert "LOOPY_PUBLIC_URL is dev-side" in result.stdout


def test_env_omits_sandbox_secrets(tmp_path):
    # Sandbox secrets ride each sandbox's env_file, not this block: the env_file values never
    # appear in the control-plane output.
    result = runner.invoke(app, ["env", str(_project(tmp_path))])
    assert "sk-ant-real" not in result.stdout
    assert "ghp_real" not in result.stdout
    assert "BASESANDBOX" not in result.stdout


def test_env_fails_on_uncompilable_project(tmp_path):
    # A project that doesn't compile (sandbox missing its required provider, E214) must not
    # emit a deploy block.
    (tmp_path / "registry.yml").write_text("sandboxes:\n  BaseSandbox:\n    image: {}\n")
    result = runner.invoke(app, ["env", str(tmp_path)])
    assert result.exit_code == 1


# ── deploy_env_block ────────────────────────────────────────────────────────────


def test_deploy_env_block_skips_laptop_and_render_keys(tmp_path):
    from loopy_cli import deploy_env_block

    project = _project(tmp_path)
    (project / "loopy.env").write_text(
        _LOOPY_ENV
        + "RENDER_API_KEY=rnd_secret\n"
        + "LOOPY_RENDER_SERVICE_ID=srv-123\n"
    )
    block = deploy_env_block(project)
    assert block["DAYTONA_API_KEY"] == "dt-real"
    assert block["LOOPY_ADMIN_TOKEN"] == "loopy_sk_admin"
    for absent in ("LOOPY_PUBLIC_URL", "REDIS_URL", "RENDER_API_KEY", "LOOPY_RENDER_SERVICE_ID"):
        assert absent not in block


def test_deploy_env_block_strips_quotes(tmp_path):
    # Regression: a quoted dotenv value must reach the platform unquoted — a stray
    # `"` in e.g. SENTRY_AUTH_TOKEN breaks the consumer at run time, not at set time.
    from loopy_cli import deploy_env_block

    project = _project(tmp_path)
    (project / "loopy.env").write_text('DAYTONA_API_KEY="dt-quoted"\n')
    assert deploy_env_block(project)["DAYTONA_API_KEY"] == "dt-quoted"
