"""`loopy init` scaffolding — the file templates for a fresh project.

Kept out of the CLI module so the (multi-line, brace-heavy) templates don't clutter the
command wiring, and so the scaffold is unit-testable as plain data. The canonical layout
mirrors `examples/codefix` (the smallest runnable loop): one `CodeTask` event → a
`claude-code` agent that edits a checkout and opens a PR. A freshly scaffolded project
compiles green out of the box — `tests/test_init_scaffold.py` guards that.
"""

from __future__ import annotations

import re
from pathlib import Path

# Sentinel replaced with the project name. Deliberately *not* `{name}`: these templates are
# full of literal braces (YAML inline maps, `{{ event.* }}` refs), so `str.format` would
# choke on them — a plain `.replace` of an unambiguous token is safer.
_NAME = "__PROJECT_NAME__"

# A project name doubles as the new directory name, so keep it a single safe path segment.
_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class InvalidProjectName(ValueError):
    """The requested project name isn't a usable single directory segment."""


def validate_project_name(name: str) -> str:
    """Return the cleaned name, or raise `InvalidProjectName` with an actionable message."""
    cleaned = name.strip()
    if not cleaned:
        raise InvalidProjectName("project name must not be empty")
    if cleaned in {".", ".."} or "/" in cleaned or "\\" in cleaned:
        raise InvalidProjectName(f"{name!r} is not a valid directory name")
    if not _NAME_RE.match(cleaned):
        raise InvalidProjectName(
            f"{name!r} must start with a letter or digit and use only letters, digits, "
            "'.', '_' or '-'"
        )
    return cleaned


_REGISTRY_YML = """\
# __PROJECT_NAME__ — a starter Loopy project. One CodeTask event drives a claude-code agent
# that edits a checkout and opens a PR. Edit freely; `loopy compile .` validates the result.

# Defaults — every agent inherits these; override a field only when needed.
defaults:
  agent:
    sandbox: Devbox
    harness: { runtime: claude-code, model: claude-sonnet-4-6 }

# Sandbox — compute + egress. `daytona` runs each agent in an isolated cloud sandbox built
# from the `image:` spec below (set DAYTONA_API_KEY in loopy.env). Swap `provider:` to `docker`
# for a fully local, hermetic run — both build from the same `image:` spec.
#   • point `repos:` at a repo you can push to (fork something, or change it to you/your-repo)
#   • `env_file:` is the gitignored dotenv injected as the sandbox's environment
sandboxes:
  Devbox:
    provider: daytona
    image: { debian_slim: "3.12", apt: [git], workdir: /home/loopy, user: loopy }
    network: [github.com, api.anthropic.com]   # git over https + the model API
    env_file: secrets/dev.env                  # gitignored; resolved at run time
    repos: [octocat/Hello-World]               # repos you name here, cloned into the workspace at acquire time

# Agents — capability comes from the sandbox, skills, injected git creds, and budget.
agents:
  Coder: { skills: [codefix] }

# Events — the bus contract. A step's `on:` may only name an event registered here.
events:
  # the task to act on — fire one by hand with `loopy trigger --event CodeTask --fields '{...}'`
  CodeTask:
    fields:
      task: str     # what to change, in prose
      branch: str   # the branch to push the edit on
  # emitted once the PR is open — a downstream workflow could subscribe with `on: PROpened`
  PROpened:
    fields:
      pr_url: url
      summary: str
"""

_OPEN_PR_MD = """\
---
on: CodeTask
agent: Coder
output:
  pr_url: url
  summary: str
emits: PROpened
budget: { wall_clock: 15, spend: { usd: 2 } }
---
A checkout of the target repository is already in your workspace — the sandbox cloned it at
startup, and a GitHub token is wired into git, so `git push` and PR creation just work.

Make the change described by the task: {{ event.task }}.

Then:
1. Create a new branch named `{{ event.branch }}`.
2. Commit your edit with a clear message.
3. Push the branch and open a pull request against the default branch. Include the loopy run
   id (the `$LOOPY_RUN_ID` environment variable) in the PR body so it can be traced to this run.

Return the pull request URL and a one-line summary of the change.
"""

_SKILL_MD = """\
# codefix

Make a focused code change in a checkout and open a pull request for it.

- Keep the diff minimal — change only what the task asks for; don't reformat untouched code.
- Match the surrounding style and conventions of the file you're editing.
- Use a descriptive branch name and a commit message that states the change, not the process.
- The PR body should say what changed and why, in a sentence or two.
- Don't push directly to the default branch; always open a PR from your branch.
"""

_SENSORS_PY = """\
from loopy import sensor
from loopy.events import CodeTask  # generated by `loopy compile` — optional, for your typechecker


@sensor(poll="10m", emits="CodeTask")  # `emits` is the contract the compiler reads
def task_queue(req) -> CodeTask:
    \"\"\"Poll a task queue for code-change requests.

    A stub to start from — a real sensor would read from Linear, a GitHub issue label, a
    spreadsheet, etc., and return a CodeTask per request. Returning None emits nothing; this
    is here so `CodeTask` has a declared producer (and you can still fire one by hand with
    `loopy trigger --event CodeTask`).
    \"\"\"
    return None
"""

_DEV_ENV = """\
# Secrets for the `Devbox` sandbox, injected as environment variables at run time. Gitignored —
# never commit this file. Lines are KEY=VALUE; values are literal (no ${VAR} interpolation).

# --- model auth (claude-code) ---
# Required for the daytona/docker providers (the built image carries no creds).
ANTHROPIC_API_KEY=sk-ant-...

# --- git auth ---
# Only needed if you are NOT using a GitHub App. `loopy auth github` injects a scoped token
# automatically; otherwise put a PAT with contents:write + pull_requests:write here.
# GITHUB_TOKEN=ghp_...

# --- only for the `local` provider (a bare subprocess inherits nothing from your shell) ---
# With the daytona/docker providers these come from the built image; leave them out.
# PATH=/usr/local/bin:/usr/bin:/bin
# HOME=/home/you
"""

_LOOPY_ENV = """\
# Control-plane credentials — the creds the loopy *engine* needs. These are NOT injected
# into sandboxes (the agent's environment is secrets/dev.env); they stay at the control
# plane. Gitignored — never commit this file. Lines are KEY=VALUE; values are literal.

# --- GitHub App (recommended git auth) ---
# Leave these commented: `loopy auth github` writes GITHUB_APP_ID + GITHUB_APP_PRIVATE_KEY
# here for you. An uncommented GITHUB_APP_ID would make that command think an App is already
# configured and refuse to run.
# GITHUB_APP_ID=
# GITHUB_APP_PRIVATE_KEY=

# --- Daytona (the default sandbox; required when a sandbox uses provider: daytona) ---
# DAYTONA_API_KEY=
# DAYTONA_API_URL=

# --- Redis (only for --bus redis) ---
# REDIS_URL=redis://localhost:6379
"""

_GITIGNORE = """\
# Generated by `loopy compile` (the loopy.events package)
/loopy/
# Compiled manifest
manifest.json

# Secrets — never commit
# control-plane creds incl. the GitHub App private key (loopy auth github)
loopy.env
# sandbox env_file(s)
secrets/
# sensor-layer secrets
sensors/.env

# Local run state (SQLite run-state DB written by `loopy run`)
.loopy/
"""

_README_MD = """\
# __PROJECT_NAME__

A Loopy project, scaffolded by `loopy init`. One `CodeTask` event drives a `claude-code`
agent that edits a checkout and opens a pull request.

## Run it

```bash
# 1. point the Devbox sandbox at a repo you can push to (registry.yml → sandboxes.Devbox.repos)

# 2. give the sandbox its secrets
#    edit secrets/dev.env and set ANTHROPIC_API_KEY

# 3. wire git auth (writes loopy.env in this project — gitignored)
loopy auth github
loopy auth status            # then visit the printed install URL to pick repos

# 4. check the above is actually done — a green compile is not a runnable project
loopy doctor

# 5. compile + fire one task (the sandbox runs on whatever registry.yml's `provider:` names)
loopy compile .              # writes manifest.json
loopy trigger manifest.json \\
  --event CodeTask \\
  --fields '{"task": "add a CONTRIBUTING.md", "branch": "codefix/contributing"}'
```

Run every command from this directory so `loopy.env` and `--root` stay in sync.
See the top-level Loopy README for the authoring model.
"""

# Relative path → template body. Written verbatim except for the `__PROJECT_NAME__` sentinel.
_FILES: dict[str, str] = {
    "registry.yml": _REGISTRY_YML,
    "workflows/codefix/open-pr.md": _OPEN_PR_MD,
    "skills/codefix/SKILL.md": _SKILL_MD,
    "sensors/sensors.py": _SENSORS_PY,
    "secrets/dev.env": _DEV_ENV,
    "loopy.env": _LOOPY_ENV,
    ".gitignore": _GITIGNORE,
    "README.md": _README_MD,
}


def scaffold_project(target: Path, name: str) -> list[Path]:
    """Write the starter project into `target`, returning the created files (relative paths).

    `target` is created if absent; an existing **non-empty** directory is refused so we never
    clobber work. The caller is expected to have validated `name` via `validate_project_name`.
    """
    target = Path(target)
    if target.exists() and any(target.iterdir()):
        raise FileExistsError(f"{target} already exists and is not empty")

    created: list[Path] = []
    for rel, template in _FILES.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(template.replace(_NAME, name))
        created.append(Path(rel))
    return sorted(created, key=lambda p: p.as_posix())
