import urllib.request

from loopy import sensor
from loopy.events import Incident  # generated by `loopy compile` — optional, for your typechecker

# The endpoint to watch. Point this at your own health URL (or read it from the environment).
HEALTH_URL = "https://example.com/health"


@sensor(poll="5m", emits="Incident")  # `emits` is the contract the compiler reads statically
def health_check(req) -> Incident | None:
    """Poll a health endpoint; emit an Incident only when it's down.

    Returning None emits nothing, so a healthy check is silent and no run starts. Only a
    non-200 (or an unreachable endpoint) turns into an `Incident` on the bus, which the
    respond workflow subscribes to. This conditional emit is the core job of a sensor:
    turn a raw signal into a typed event, and only when it matters.
    """
    try:
        with urllib.request.urlopen(HEALTH_URL, timeout=10) as resp:
            status = resp.status
    except Exception:
        status = 0  # unreachable, treat as down

    if status == 200:
        return None  # healthy, nothing to emit
    return Incident(url=HEALTH_URL, status=status)
